### ISSUE TITLE
Basic Editor based on Codemirror

### ISSUE THREAD

**Issue by h3ssto** [OBDDimal/PyUVL#2]
Create a basic web-based editor using 
* [Codemirror](https://codemirror.net/)
* ~~[LIT](https://lit.dev/)~~ (plain HTML for now)

Supported actions:
* Open / Save UVL file
* Syntax Highlighting + Auto Completion (see #1)

**Comment by Ateyu** [comment]
The language must be removed and should be integrated as a  dependency. 
https://github.com/OBDDimal/codemirror-lang-uvl
