### ISSUE TITLE
Add Tests for all UVL Language Levels

### ISSUE THREAD

**Issue by h3ssto** [OBDDimal/PyUVL#4]
Follow the guide on testing Lezer Parsers: https://lezer.codemirror.net/examples/test/

See the UVL examples referencend here: https://github.com/Universal-Variability-Language/java-fm-metamodel/blob/refactoring_metamodel/src/test/java/de/vill/parsing/ParsingTests.java and especially the files in https://github.com/Universal-Variability-Language/java-fm-metamodel/tree/refactoring_metamodel/src/test/resources/parsing

**Comment by Ateyu** [comment]
Issue completed and merged to issue-2
